import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import svelteParser from 'svelte-eslint-parser';

export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.astro/**',
      'apps/desktop/build/**',
      // Generated by Wails from the Go bindings.
      'apps/desktop/frontend/wailsjs/**',
      'perf/fixtures/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,
  ...svelte.configs['flat/recommended'],

  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
          // `const { id, ...rest } = row` is how fields are dropped from a
          // payload; the named binding is the point, not an oversight.
          ignoreRestSiblings: true,
        },
      ],
      // Deliberately ignoring a failure is a normal pattern here (best-effort
      // cleanup, optional platform APIs). An empty block anywhere else is a bug.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // A quoted literal reads better than an entity-escaped attribute when the
      // value is itself a snippet of code containing quotes.
      'svelte/no-useless-mustaches': 'off',
    },
  },

  {
    // Store modules take part in rune reactivity, so a bare `host.foo;` is a
    // deliberate subscription rather than a statement with no effect.
    files: ['apps/desktop/frontend/src/lib/stores/**'],
    rules: {
      '@typescript-eslint/no-unused-expressions': 'off',
    },
  },

  {
    // `.svelte.ts` modules use runes too, so they need the Svelte parser rather
    // than the plain TypeScript one.
    files: ['**/*.svelte', '**/*.svelte.ts'],
    languageOptions: {
      parser: svelteParser,
      parserOptions: { parser: tseslint.parser },
    },
    rules: {
      // Runes track dependencies by reading them, so a bare `value;` inside an
      // $effect is the intended way to subscribe — not a dead expression.
      '@typescript-eslint/no-unused-expressions': 'off',
      // Both are worth fixing but too widespread to gate CI on today. They stay
      // visible as warnings so new code doesn't add to the pile.
      'svelte/require-each-key': 'warn',
      'svelte/prefer-svelte-reactivity': 'warn',
    },
  },
];
