// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['api']['App']['AppInfo']();
}

export function ApplyUpdate(arg1) {
  return window['go']['api']['App']['ApplyUpdate'](arg1);
}

export function AuthorizeOAuth2(arg1) {
  return window['go']['api']['App']['AuthorizeOAuth2'](arg1);
}

export function CancelQuit() {
  return window['go']['api']['App']['CancelQuit']();
}

export function CancelRequest(arg1) {
  return window['go']['api']['App']['CancelRequest'](arg1);
}

export function CheckForUpdate() {
  return window['go']['api']['App']['CheckForUpdate']();
}

export function ClearCookies(arg1) {
  return window['go']['api']['App']['ClearCookies'](arg1);
}

export function ClearVariables() {
  return window['go']['api']['App']['ClearVariables']();
}

export function ClipboardGet() {
  return window['go']['api']['App']['ClipboardGet']();
}

export function ClipboardSet(arg1) {
  return window['go']['api']['App']['ClipboardSet'](arg1);
}

export function ConfirmQuit() {
  return window['go']['api']['App']['ConfirmQuit']();
}

export function CreateLocalWorkspaceRoot(arg1, arg2, arg3) {
  return window['go']['api']['App']['CreateLocalWorkspaceRoot'](arg1, arg2, arg3);
}

export function DefaultWorkspaceLocation() {
  return window['go']['api']['App']['DefaultWorkspaceLocation']();
}

export function DeleteCookie(arg1, arg2) {
  return window['go']['api']['App']['DeleteCookie'](arg1, arg2);
}

export function DeleteVariable(arg1) {
  return window['go']['api']['App']['DeleteVariable'](arg1);
}

export function FetchOAuth2Token(arg1) {
  return window['go']['api']['App']['FetchOAuth2Token'](arg1);
}

export function GetEnvironment() {
  return window['go']['api']['App']['GetEnvironment']();
}

export function GetVariables() {
  return window['go']['api']['App']['GetVariables']();
}

export function GitAbortOperation() {
  return window['go']['api']['App']['GitAbortOperation']();
}

export function GitAddRemote(arg1, arg2) {
  return window['go']['api']['App']['GitAddRemote'](arg1, arg2);
}

export function GitAuthConfig(arg1) {
  return window['go']['api']['App']['GitAuthConfig'](arg1);
}

export function GitBranches() {
  return window['go']['api']['App']['GitBranches']();
}

export function GitCheckoutBranch(arg1) {
  return window['go']['api']['App']['GitCheckoutBranch'](arg1);
}

export function GitClearToken(arg1) {
  return window['go']['api']['App']['GitClearToken'](arg1);
}

export function GitCloneWorkspace(arg1, arg2, arg3) {
  return window['go']['api']['App']['GitCloneWorkspace'](arg1, arg2, arg3);
}

export function GitCloneWorkspaceWithAuth(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['api']['App']['GitCloneWorkspaceWithAuth'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GitCloneWorkspaceWithMode(arg1, arg2, arg3, arg4) {
  return window['go']['api']['App']['GitCloneWorkspaceWithMode'](arg1, arg2, arg3, arg4);
}

export function GitCommitDiff(arg1) {
  return window['go']['api']['App']['GitCommitDiff'](arg1);
}

export function GitCommitLog(arg1) {
  return window['go']['api']['App']['GitCommitLog'](arg1);
}

export function GitCommitLogPage(arg1, arg2) {
  return window['go']['api']['App']['GitCommitLogPage'](arg1, arg2);
}

export function GitCommitWorkspace(arg1) {
  return window['go']['api']['App']['GitCommitWorkspace'](arg1);
}

export function GitCommitWorkspaceFiles(arg1, arg2) {
  return window['go']['api']['App']['GitCommitWorkspaceFiles'](arg1, arg2);
}

export function GitConflictFile(arg1) {
  return window['go']['api']['App']['GitConflictFile'](arg1);
}

export function GitContinueOperation(arg1) {
  return window['go']['api']['App']['GitContinueOperation'](arg1);
}

export function GitCreateBranch(arg1, arg2) {
  return window['go']['api']['App']['GitCreateBranch'](arg1, arg2);
}

export function GitCreateTrackingBranch(arg1, arg2) {
  return window['go']['api']['App']['GitCreateTrackingBranch'](arg1, arg2);
}

export function GitDeleteBranch(arg1, arg2, arg3) {
  return window['go']['api']['App']['GitDeleteBranch'](arg1, arg2, arg3);
}

export function GitDiff(arg1) {
  return window['go']['api']['App']['GitDiff'](arg1);
}

export function GitDiscardWorkspaceChanges() {
  return window['go']['api']['App']['GitDiscardWorkspaceChanges']();
}

export function GitDiscardWorkspaceFile(arg1) {
  return window['go']['api']['App']['GitDiscardWorkspaceFile'](arg1);
}

export function GitDiscardWorkspaceFiles(arg1) {
  return window['go']['api']['App']['GitDiscardWorkspaceFiles'](arg1);
}

export function GitFetchWorkspace() {
  return window['go']['api']['App']['GitFetchWorkspace']();
}

export function GitForcePushWorkspace(arg1) {
  return window['go']['api']['App']['GitForcePushWorkspace'](arg1);
}

export function GitInitWorkspace() {
  return window['go']['api']['App']['GitInitWorkspace']();
}

export function GitOutgoingChanges() {
  return window['go']['api']['App']['GitOutgoingChanges']();
}

export function GitPullBranch(arg1) {
  return window['go']['api']['App']['GitPullBranch'](arg1);
}

export function GitPullWorkspace() {
  return window['go']['api']['App']['GitPullWorkspace']();
}

export function GitPullWorkspaceWithStrategy(arg1) {
  return window['go']['api']['App']['GitPullWorkspaceWithStrategy'](arg1);
}

export function GitPushWorkspace(arg1) {
  return window['go']['api']['App']['GitPushWorkspace'](arg1);
}

export function GitRemoteUrl(arg1) {
  return window['go']['api']['App']['GitRemoteUrl'](arg1);
}

export function GitRenameBranch(arg1, arg2, arg3) {
  return window['go']['api']['App']['GitRenameBranch'](arg1, arg2, arg3);
}

export function GitResolveConflictFile(arg1, arg2, arg3) {
  return window['go']['api']['App']['GitResolveConflictFile'](arg1, arg2, arg3);
}

export function GitSetRemoteUrl(arg1, arg2) {
  return window['go']['api']['App']['GitSetRemoteUrl'](arg1, arg2);
}

export function GitSetSshKey(arg1, arg2) {
  return window['go']['api']['App']['GitSetSshKey'](arg1, arg2);
}

export function GitSshUrlFor(arg1) {
  return window['go']['api']['App']['GitSshUrlFor'](arg1);
}

export function GitStageWorkspaceFiles() {
  return window['go']['api']['App']['GitStageWorkspaceFiles']();
}

export function GitStashPopWorkspace(arg1) {
  return window['go']['api']['App']['GitStashPopWorkspace'](arg1);
}

export function GitStashWorkspace(arg1) {
  return window['go']['api']['App']['GitStashWorkspace'](arg1);
}

export function GitStatus() {
  return window['go']['api']['App']['GitStatus']();
}

export function GitStoreToken(arg1, arg2, arg3) {
  return window['go']['api']['App']['GitStoreToken'](arg1, arg2, arg3);
}

export function GitTestRemote(arg1) {
  return window['go']['api']['App']['GitTestRemote'](arg1);
}

export function GitTokenInfo(arg1) {
  return window['go']['api']['App']['GitTokenInfo'](arg1);
}

export function GrpcDiscover(arg1) {
  return window['go']['api']['App']['GrpcDiscover'](arg1);
}

export function Hide() {
  return window['go']['api']['App']['Hide']();
}

export function ListCookies(arg1) {
  return window['go']['api']['App']['ListCookies'](arg1);
}

export function LoadRequestStore() {
  return window['go']['api']['App']['LoadRequestStore']();
}

export function LoadWorkspaceDiagnostics() {
  return window['go']['api']['App']['LoadWorkspaceDiagnostics']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['api']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenDirectoryDialogWithDefault(arg1, arg2) {
  return window['go']['api']['App']['OpenDirectoryDialogWithDefault'](arg1, arg2);
}

export function OpenFileDialog(arg1) {
  return window['go']['api']['App']['OpenFileDialog'](arg1);
}

export function OpenWorkspaceRoot(arg1) {
  return window['go']['api']['App']['OpenWorkspaceRoot'](arg1);
}

export function Quit() {
  return window['go']['api']['App']['Quit']();
}

export function ReadCollectionTextFiles(arg1) {
  return window['go']['api']['App']['ReadCollectionTextFiles'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['api']['App']['ReadTextFile'](arg1);
}

export function ReadWorkspaceYAMLFile(arg1) {
  return window['go']['api']['App']['ReadWorkspaceYAMLFile'](arg1);
}

export function RefreshOAuth2Token(arg1) {
  return window['go']['api']['App']['RefreshOAuth2Token'](arg1);
}

export function RestartApp() {
  return window['go']['api']['App']['RestartApp']();
}

export function SSEConnect(arg1, arg2) {
  return window['go']['api']['App']['SSEConnect'](arg1, arg2);
}

export function SSEDisconnect(arg1) {
  return window['go']['api']['App']['SSEDisconnect'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['api']['App']['SaveFileDialog'](arg1, arg2);
}

export function SaveRequestStore(arg1) {
  return window['go']['api']['App']['SaveRequestStore'](arg1);
}

export function SaveRequestStoreWithError(arg1) {
  return window['go']['api']['App']['SaveRequestStoreWithError'](arg1);
}

export function SaveWorkspaceSecrets(arg1) {
  return window['go']['api']['App']['SaveWorkspaceSecrets'](arg1);
}

export function SendGrpcRequest(arg1) {
  return window['go']['api']['App']['SendGrpcRequest'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['api']['App']['SendRequest'](arg1);
}

export function SendRequestToFile(arg1, arg2) {
  return window['go']['api']['App']['SendRequestToFile'](arg1, arg2);
}

export function SetAppThemeBackground(arg1, arg2) {
  return window['go']['api']['App']['SetAppThemeBackground'](arg1, arg2);
}

export function SetDefaultWorkspaceLocation(arg1) {
  return window['go']['api']['App']['SetDefaultWorkspaceLocation'](arg1);
}

export function SetEnvironment(arg1) {
  return window['go']['api']['App']['SetEnvironment'](arg1);
}

export function SetEnvironmentVar(arg1, arg2) {
  return window['go']['api']['App']['SetEnvironmentVar'](arg1, arg2);
}

export function SetVariable(arg1, arg2) {
  return window['go']['api']['App']['SetVariable'](arg1, arg2);
}

export function Show() {
  return window['go']['api']['App']['Show']();
}

export function SocketIOConnect(arg1, arg2) {
  return window['go']['api']['App']['SocketIOConnect'](arg1, arg2);
}

export function SocketIODisconnect(arg1) {
  return window['go']['api']['App']['SocketIODisconnect'](arg1);
}

export function SocketIOEmit(arg1, arg2) {
  return window['go']['api']['App']['SocketIOEmit'](arg1, arg2);
}

export function UpsertCookie(arg1, arg2) {
  return window['go']['api']['App']['UpsertCookie'](arg1, arg2);
}

export function UseLocalWorkspaceStore() {
  return window['go']['api']['App']['UseLocalWorkspaceStore']();
}

export function WebSocketConnect(arg1, arg2) {
  return window['go']['api']['App']['WebSocketConnect'](arg1, arg2);
}

export function WebSocketDisconnect(arg1) {
  return window['go']['api']['App']['WebSocketDisconnect'](arg1);
}

export function WebSocketSend(arg1, arg2) {
  return window['go']['api']['App']['WebSocketSend'](arg1, arg2);
}

export function WriteCollectionTextFiles(arg1, arg2) {
  return window['go']['api']['App']['WriteCollectionTextFiles'](arg1, arg2);
}

export function WriteWorkspaceYAMLFile(arg1, arg2) {
  return window['go']['api']['App']['WriteWorkspaceYAMLFile'](arg1, arg2);
}
