// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {api} from '../models';

export function AppInfo():Promise<model.AppInfo>;

export function ApplyUpdate(arg1:model.UpdateInfo):Promise<string>;

export function AuthorizeOAuth2(arg1:model.AuthConfig):Promise<model.OAuth2TokenResponse>;

export function CancelQuit():Promise<void>;

export function CancelRequest(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<model.UpdateCheckResult>;

export function ClearCookies(arg1:string):Promise<Array<model.Cookie>>;

export function ClearVariables():Promise<void>;

export function ClipboardGet():Promise<string>;

export function ClipboardSet(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function CreateLocalWorkspaceRoot(arg1:string,arg2:string,arg3:string):Promise<api.WorkspaceOpenResult>;

export function DefaultWorkspaceLocation():Promise<api.DefaultWorkspaceLocationResult>;

export function DeleteCookie(arg1:string,arg2:model.Cookie):Promise<model.CookieJarResult>;

export function DeleteVariable(arg1:string):Promise<void>;

export function FetchOAuth2Token(arg1:model.AuthConfig):Promise<model.OAuth2TokenResponse>;

export function GetEnvironment():Promise<Record<string, string>>;

export function GetVariables():Promise<Record<string, string>>;

export function GitAbortOperation():Promise<api.WorkspaceOpenResult>;

export function GitAddRemote(arg1:string,arg2:string):Promise<api.GitOperationResult>;

export function GitAuthConfig(arg1:string):Promise<api.GitAuthConfigResult>;

export function GitBranches():Promise<api.GitBranchListResult>;

export function GitCheckoutBranch(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitClearToken(arg1:string):Promise<api.GitOperationResult>;

export function GitCloneWorkspace(arg1:string,arg2:string,arg3:string):Promise<api.WorkspaceOpenResult>;

export function GitCloneWorkspaceWithAuth(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<api.WorkspaceOpenResult>;

export function GitCloneWorkspaceWithMode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.WorkspaceOpenResult>;

export function GitCommitDiff(arg1:string):Promise<api.GitDiffResult>;

export function GitCommitLog(arg1:number):Promise<api.GitLogResult>;

export function GitCommitLogPage(arg1:number,arg2:number):Promise<api.GitLogResult>;

export function GitCommitWorkspace(arg1:string):Promise<api.GitOperationResult>;

export function GitCommitWorkspaceFiles(arg1:Array<string>,arg2:string):Promise<api.GitOperationResult>;

export function GitConflictFile(arg1:string):Promise<api.GitConflictFileResult>;

export function GitContinueOperation(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitCreateBranch(arg1:string,arg2:string):Promise<api.WorkspaceOpenResult>;

export function GitCreateTrackingBranch(arg1:string,arg2:string):Promise<api.WorkspaceOpenResult>;

export function GitDeleteBranch(arg1:string,arg2:boolean,arg3:boolean):Promise<api.GitOperationResult>;

export function GitDiff(arg1:string):Promise<api.GitDiffResult>;

export function GitDiscardWorkspaceChanges():Promise<api.WorkspaceOpenResult>;

export function GitDiscardWorkspaceFile(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitDiscardWorkspaceFiles(arg1:Array<string>):Promise<api.WorkspaceOpenResult>;

export function GitFetchWorkspace():Promise<api.GitWorkspaceStatus>;

export function GitForcePushWorkspace(arg1:string):Promise<api.GitOperationResult>;

export function GitInitWorkspace():Promise<api.GitOperationResult>;

export function GitOutgoingChanges():Promise<api.GitDiffResult>;

export function GitPullBranch(arg1:string):Promise<api.GitOperationResult>;

export function GitPullWorkspace():Promise<api.WorkspaceOpenResult>;

export function GitPullWorkspaceWithStrategy(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitPushWorkspace(arg1:string):Promise<api.GitOperationResult>;

export function GitRemoteUrl(arg1:string):Promise<string>;

export function GitRenameBranch(arg1:string,arg2:string,arg3:boolean):Promise<api.GitOperationResult>;

export function GitResolveConflictFile(arg1:string,arg2:string,arg3:string):Promise<api.GitOperationResult>;

export function GitSetRemoteUrl(arg1:string,arg2:string):Promise<api.GitOperationResult>;

export function GitSetSshKey(arg1:string,arg2:string):Promise<api.GitOperationResult>;

export function GitSshUrlFor(arg1:string):Promise<string>;

export function GitStageWorkspaceFiles():Promise<api.GitOperationResult>;

export function GitStashPopWorkspace(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitStashWorkspace(arg1:string):Promise<api.WorkspaceOpenResult>;

export function GitStatus():Promise<api.GitWorkspaceStatus>;

export function GitStoreToken(arg1:string,arg2:string,arg3:string):Promise<api.GitOperationResult>;

export function GitTestRemote(arg1:string):Promise<api.GitOperationResult>;

export function GitTokenInfo(arg1:string):Promise<api.GitTokenInfoResult>;

export function GrpcDiscover(arg1:model.GrpcRequest):Promise<model.GrpcServiceDefinition>;

export function Hide():Promise<void>;

export function ListCookies(arg1:string):Promise<Array<model.Cookie>>;

export function LoadRequestStore():Promise<string>;

export function LoadWorkspaceDiagnostics():Promise<Array<api.WorkspaceDiagnostic>>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenDirectoryDialogWithDefault(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function OpenWorkspaceRoot(arg1:string):Promise<api.WorkspaceOpenResult>;

export function Quit():Promise<void>;

export function ReadCollectionTextFiles(arg1:string):Promise<api.CollectionTextFilesResult>;

export function ReadTextFile(arg1:string):Promise<string>;

export function ReadWorkspaceYAMLFile(arg1:string):Promise<api.WorkspaceYAMLFileResult>;

export function RefreshOAuth2Token(arg1:model.AuthConfig):Promise<model.OAuth2TokenResponse>;

export function RestartApp():Promise<void>;

export function SSEConnect(arg1:string,arg2:model.HttpRequest):Promise<void>;

export function SSEDisconnect(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SaveRequestStore(arg1:string):Promise<boolean>;

export function SaveRequestStoreWithError(arg1:string):Promise<api.SaveRequestStoreResult>;

export function SaveWorkspaceSecrets(arg1:Record<string, string>):Promise<api.WorkspaceOpenResult>;

export function SendGrpcRequest(arg1:model.GrpcRequest):Promise<model.GrpcResponse>;

export function SendRequest(arg1:model.HttpRequest):Promise<model.HttpResponse>;

export function SendRequestToFile(arg1:model.HttpRequest,arg2:string):Promise<api.DownloadResult>;

export function SetAppThemeBackground(arg1:string,arg2:string):Promise<void>;

export function SetDefaultWorkspaceLocation(arg1:string):Promise<api.DefaultWorkspaceLocationResult>;

export function SetEnvironment(arg1:Record<string, string>):Promise<void>;

export function SetEnvironmentVar(arg1:string,arg2:string):Promise<void>;

export function SetVariable(arg1:string,arg2:string):Promise<void>;

export function Show():Promise<void>;

export function SocketIOConnect(arg1:string,arg2:model.HttpRequest):Promise<void>;

export function SocketIODisconnect(arg1:string):Promise<void>;

export function SocketIOEmit(arg1:string,arg2:model.SocketIOEmitMessage):Promise<model.SocketIOEmitResult>;

export function UpsertCookie(arg1:string,arg2:model.Cookie):Promise<model.CookieJarResult>;

export function UseLocalWorkspaceStore():Promise<api.WorkspaceOpenResult>;

export function WebSocketConnect(arg1:string,arg2:model.HttpRequest):Promise<void>;

export function WebSocketDisconnect(arg1:string):Promise<void>;

export function WebSocketSend(arg1:string,arg2:model.WebSocketSendMessage):Promise<model.WebSocketSendResult>;

export function WriteCollectionTextFiles(arg1:string,arg2:Array<api.CollectionTextFile>):Promise<string>;

export function WriteWorkspaceYAMLFile(arg1:string,arg2:string):Promise<api.WorkspaceOpenResult>;
